version: '3.7'

services:
  node:
    image: node:14
    working_dir: /home/node/app
    user: '1000'
    command: /bin/sh -c "yarn && yarn test --watch"
    volumes:
      - ./:/home/node/app
    tty: true
